## Quick View of Python: NumPy
**Author: Aishwarya Gulve**

**What are NumPy arrays?**

It is a python package stands for 'Numerical Python'. It is used for scientific computing, which contains a powerful n-dimentional array object.

**Install NumPy: Go to your command prompt and type "pip install numpy"**

In [1]:
# import numpy
import numpy as np

NumPy is usually imported under the np alias. In Python alias are an alternate name for referring to the same thing.

**Check the version of the NumPy**

In [2]:
print(np.__version__)

1.18.1


**Create Python array and NumPy array**

In [3]:
# create python array
py_array = [10, 11, 12, 13, 14, 15]
print(py_array)

[10, 11, 12, 13, 14, 15]


In [4]:
# create numpy array
num_array = np.array([10, 11, 12, 13, 14, 15])
print(num_array)

[10 11 12 13 14 15]


**Note:**<br>
We can not see much difference between both the arrays. Why do we use numpy array instead of regular array?<br>
The answer is that numpy array are better interms of faster computation and ease of manipulation.

### NumPy ndarray object

**Dimensions in arrays**

* 0-dimentional array

In [5]:
# create a 0-d array with value 65
array_0d = np.array(65)
array_0d

array(65)

* 1-dimentional array

In [6]:
# create a 1-d array
array_1d = np.array([23, 44, 56, 63])
array_1d

array([23, 44, 56, 63])

* 2-dimentional array

In [7]:
# create a 2-d array
array_2d = np.array([[11,12,13], [21,22,23]])
array_2d

array([[11, 12, 13],
       [21, 22, 23]])

* 3-dimentional array

In [8]:
# create a 3-d array
array_3d = np.array([[[11,12,13], [14, 15, 16]], [[21, 22, 23], [24, 25, 26]]])
array_3d

array([[[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 23],
        [24, 25, 26]]])

* Number of Dimensions

**Use ndim to check the dimensions of the array**

In [9]:
# check the dimensions of 1-d array
array_1d.ndim

1

In [10]:
# check the dimension of 2-d array
array_2d.ndim

2

In [11]:
# check the dimension of 3-d array
array_3d.ndim

3

* Higher Dimensional array

In [12]:
# create an array with 5 dimensions
higher_dim_array = np.array([11,12,13,14], ndmin=5)
higher_dim_array

array([[[[[11, 12, 13, 14]]]]])

### NumPy array indexing

* Access 1-d array

Indexes starts with 0, means that first element has index 0, and the second has index 1

In [13]:
# display the one dimentional array
array_1d

array([23, 44, 56, 63])

In [14]:
# extract the first element from the array
array_1d[0]

23

In [15]:
# extract the third element from the array
array_1d[2]

56

* Access 2-d array

In [16]:
# display 2-d array
array_2d

array([[11, 12, 13],
       [21, 22, 23]])

In [17]:
# extract first element from the first row
array_2d[0,0]

11

In [18]:
# extract second elemnent from the second row
array_2d[0, 1]

12

* Access 3-D Arrays

In [19]:
# display 3-d array
array_3d

array([[[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 23],
        [24, 25, 26]]])

In [20]:
# extract first element of the first array of the first array
array_3d[0,0,0]

11

In [21]:
# extract seccond element of the first array of the first array
array_3d[0,0,1]

12

In [22]:
# extract first element of the second array of the first array
array_3d[1,0,0]

21

In [23]:
# extract the second element of the second array of the first array
array_3d[1,0,1]

22

* Negative indexing

In [24]:
# display 2-d array
array_2d

array([[11, 12, 13],
       [21, 22, 23]])

In [25]:
# extract second last element from the second array
array_2d[1,-2]

22

### Array slicing

In [26]:
# display 1-d array
array_1d

array([23, 44, 56, 63])

In [27]:
# slice elements from index 1 to index 3
array_1d[1:3]

array([44, 56])

In [28]:
# slice elements from index 1
array_1d[1:]

array([44, 56, 63])

In [29]:
# slice elements from the beginning to index 3
array_1d[:3]

array([23, 44, 56])

* Negative slicing

In [30]:
# slice from the index 4 from the end to index 1 from the end
array_1d[-4:-1]

array([23, 44, 56])

* Use the step value to determine the step of the slicing 

In [31]:
# return every other element from index 1 to index 4
array_1d[1:4:2]

array([44, 63])

In [32]:
# return every other element from the entire array
array_1d[::2]

array([23, 56])

* Slicing 2-d array

In [33]:
# create a 2-d array
array_2d = np.array([[11,22,33,44,55], [21,22,23,24,25]])
array_2d

array([[11, 22, 33, 44, 55],
       [21, 22, 23, 24, 25]])

In [34]:
# from the 2nd array, slice elements from index 1 to index 5
array_2d[1, 1:5]

array([22, 23, 24, 25])

In [35]:
# from both array, return index 3
array_2d[0:2, 3]

array([44, 24])

In [36]:
# from both elements, slice index 0 to slice index 3
array_2d[0:2, 0:3]

array([[11, 22, 33],
       [21, 22, 23]])

### NumPy data types

NumPy has some extra data types than python. Following is a list of data types in numpy.

* **Data types** 
<table>
<tr>
<th>i</th>
<th>integer</th>
</tr>
<tr>
<th>b</th>
<th>boolean</th>
</tr>
<tr>
<th>u</th>
<th>unsigned integer</th>
</tr>
<tr>
<th>f</th>
<th>float</th>
</tr>
<tr>
<th>c</th>
<th>complex float</th>
</tr>
<tr>
<th>m</th>
<th>timedelta</th>
</tr>
<tr>
<th>M</th>
<th>datetime</th>
</tr>   
<tr>
<th>O</th>
<th>object</th>
</tr> 
<tr>
<th>S</th>
<th>string</th>
</tr> 
<tr>
<th>U</th>
<th>unicode string</th>
</tr>
<tr>
<th>V</th>
<th>fixed chunk of memory for the other type</th>
</tr> 
</table>

In [37]:
# create array
score_arr = np.array([100, 96, 78, 88, 89])

# data type of array object
score_arr.dtype

dtype('int32')

In [38]:
# create array
subject_arr = np.array(['Maths', 'English', 'Science', 'History'])

# data type of array object
subject_arr.dtype

dtype('<U7')

* Create arrays with a defined data type

In [39]:
# create an array with string data type
id_array = np.array([101, 102, 104, 105], dtype='S')

# data type of the array object
id_array.dtype

dtype('S3')

In [40]:
# create an array with data type 2 bytes integer
score_array = np.array([100, 96, 78, 88, 89], dtype='i2')

# data type of the array object
score_array.dtype

dtype('int16')

**Data type conversion**

Use astype() function to change the data type of the array. The astype() function creates a copy of the array, and allows to specify the data type as a parameter.

In [41]:
# change the data type from float to integer


points_arr = np.array([1.3, 1.2, 1.6, 1.7])
# check the data type
print(points_arr.dtype)


# change the data type
new_points_arr = points_arr.astype('i')
# check the data type
print(new_points_arr.dtype)

float64
int32


In [42]:
# change the data type from integer to boolean


score_array = np.array([100, 96, 78, 88, 89])
# data type of the array object
print(score_array.dtype)

# change the data type
new_score_array = score_array.astype(bool)
# check the data type
print(new_score_array.dtype)


int32
bool


### NumPy copy and view

View: The view is just view of original array<br>
Copy: The copy is new array

* copy()

**Make the copy of original array, change the value of original array, display both the arrays**

In [43]:
# create an array
score_array = np.array([100, 96, 78, 88, 89])

# create a copy of score array
copy_score_array = score_array.copy()

# change the value of original array
score_array[0] = 99

# display both the arrays
print(score_array)
print(copy_score_array)

[99 96 78 88 89]
[100  96  78  88  89]


We can see the copy is not affected by the changes made to the original array.

* view()

In [44]:
# create an array
score_array = np.array([100, 96, 78, 88, 89])
# view the original array
view_score_array = score_array.view()

# change the value of original array
score_array[0] = 99 

# display both the arrays
print(score_array)
print(view_score_array)

[99 96 78 88 89]
[99 96 78 88 89]


We can see the view is affected by the changes made to the original array.

* Changes in view()

In [45]:
# create an array
score_array = np.array([100, 96, 78, 88, 89])
# view the original array
view_score_array = score_array.view()

# change the value of original array
view_score_array[0] = 99 

# display both the arrays
print(score_array)
print(view_score_array)

[99 96 78 88 89]
[99 96 78 88 89]


We can see the original array is affected by the changes made to the view.

**Check if array owns it's data**

As we know, copies owns data, and views does not own the data, but how can we know this?<br>
The attribute base returns None if the array owns the data.

In [46]:
# create an array
score_array = np.array([100, 96, 78, 88, 89])

copy_score_array = score_array.copy()

view_score_array = score_array.view()

print(copy_score_array.base)
print(view_score_array.base)

None
[100  96  78  88  89]


### NumPy array shape

Use shape attribute to check shape of the array

In [47]:
# create an 2-d array
score_2d = np.array([[87, 99, 85, 76], [57, 74, 83, 65]])
score_2d.shape

(2, 4)

In [48]:
# create array with 5 dimension
score_5d = np.array([101,102,103,104,105], ndmin=5)
print(score_5d)

# check the shape
score_5d.shape

[[[[[101 102 103 104 105]]]]]


(1, 1, 1, 1, 5)

### NumPy array reshape

Changing the shape of array is called reshaping

**1-D to 2-D**

In [49]:
# reshape the following 1-D array to 2-D array
array_1d = np.array([11,12,13,14,15,16,17,18])
print("Display 1-d array:",array_1d)

# reshape the array
new_array_2d = array_1d.reshape(4,2)

# display new 2d array
print("Diaplay new 2-d array:\n" ,new_array_2d)

Display 1-d array: [11 12 13 14 15 16 17 18]
Diaplay new 2-d array:
 [[11 12]
 [13 14]
 [15 16]
 [17 18]]


This outermost dimension have 4 arrays, each with 2 elements.

**1-D to 3-D**

In [50]:
# reshape following 1-d array to 2-d array
array_1d = np.array([11,12,13,14,15,16,17,18])
print("Display 1-d array:",array_1d)

# reshape the array
new_array_3d = array_1d.reshape(2, 2, 2)

# display new 3d array
print("Diaplay new 3-d array:\n" ,new_array_3d)

Display 1-d array: [11 12 13 14 15 16 17 18]
Diaplay new 3-d array:
 [[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]


This outermost dimension will have 2 arrays that contains 2 arrays, each with 2 elements.

**Is is possible to reshape array into any shape?**

Try converting 1D array with 8 elements to a 2D array with 4 elements in each dimension. It will throw an error.

In [51]:
# reshape the following 1-D array to 2-D array
array_1d = np.array([11,12,13,14,15,16,17,18])
print("Display 1-d array:",array_1d)

# reshape the array
new_array_2d = array_1d.reshape(4,4)

# display new 2d array
print("Diaplay new 2-d array:\n" ,new_array_2d)

Display 1-d array: [11 12 13 14 15 16 17 18]


ValueError: cannot reshape array of size 8 into shape (4,4)

**Flattening the arrays**

It means converting a multidimentional array into 1D array

In [52]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

Use -1 to convert multidimentional array to 1d array

In [53]:
array_2d.reshape(-1)

array([1, 2, 3, 4, 5, 6])

### NumPy join array

The concatinating two or more arrays in a single array is called joining.

In [54]:
# create two different arrays
array_1 = np.array([101, 102, 103, 104, 105])
array_2 = np.array([106, 107, 108, 109, 110])

# concatenate two arrays
new_array = np.concatenate((array_1, array_2))

# display the new array
new_array

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [55]:
# create two dimentional array
array1_2d = np.array([[101, 102], [103, 104]])
print("Display first array:\n",array1_2d)

array2_2d = np.array([[105, 106], [107, 108]])
print("Display second array:\n",array2_2d)

# concatenate two arrays
new_array = np.concatenate((array1_2d, array2_2d), axis=1)
print("Join two 2-D arrays along rows (axis=1):\n",new_array)

Display first array:
 [[101 102]
 [103 104]]
Display second array:
 [[105 106]
 [107 108]]
Join two 2-D arrays along rows (axis=1):
 [[101 102 105 106]
 [103 104 107 108]]


**Stack functions**

It is used to join a sequence of same dimension array along a new axis

In [56]:
array_1 = np.array([11, 12, 13])
print("Display first array:\n",array_1)

array_2 = np.array([14, 15, 16])
print("Display second array:\n",array_2)

new_array = np.stack((array_1, array_2), axis=1)
new_array

Display first array:
 [11 12 13]
Display second array:
 [14 15 16]


array([[11, 14],
       [12, 15],
       [13, 16]])

Use `hstack()` to stack arrays along rows

In [57]:
array_1 = np.array([11, 12, 13])
print("Display first array:\n",array_1)

array_2 = np.array([14, 15, 16])
print("Display second array:\n",array_2)

new_array = np.hstack((array_1, array_2))
new_array

Display first array:
 [11 12 13]
Display second array:
 [14 15 16]


array([11, 12, 13, 14, 15, 16])

Use `vstack()` to stack arrays along columns

In [58]:
array_1 = np.array([11, 12, 13])
print("Display first array:\n",array_1)

array_2 = np.array([14, 15, 16])
print("Display second array:\n",array_2)

new_array = np.vstack((array_1, array_2))
new_array

Display first array:
 [11 12 13]
Display second array:
 [14 15 16]


array([[11, 12, 13],
       [14, 15, 16]])

Use `dstack()` to stack arrays along height

In [59]:
array_1 = np.array([11, 12, 13])
print("Display first array:\n",array_1)

array_2 = np.array([14, 15, 16])
print("Display second array:\n",array_2)

new_array = np.dstack((array_1, array_2))
new_array

Display first array:
 [11 12 13]
Display second array:
 [14 15 16]


array([[[11, 14],
        [12, 15],
        [13, 16]]])

### NumPy split array

Use `array_split()` for splitting arrays

In [60]:
# create array
my_array = np.array([111, 112, 113, 114])

# split the given array into two parts
new_array = np.array_split(my_array, 2)
new_array

[array([111, 112]), array([113, 114])]

Split the array into three parts

In [61]:
# create array
my_array = np.array([111, 112, 113, 114])

# split the given array into three parts
new_array = np.array_split(my_array, 3)
new_array

[array([111, 112]), array([113]), array([114])]

If the array has less elements than required, it will adjust from the end accordingly.



We can access the above splitted arrays

In [62]:
print(new_array[0])
print(new_array[1])

[111 112]
[113]


The split method not adjust the elements when elements are less in source array for splitting

In [63]:
# create array
my_array = np.array([111, 112, 113, 114])

# split the given array into three parts
new_array = np.split(my_array, 3)
new_array

ValueError: array split does not result in an equal division

**Splitting 2-D array**

In [64]:
my_array = np.array([[11, 12], [13, 14], [15, 16], [17, 18]])

print(my_array)

new_array = np.array_split(my_array, 2)

new_array

[[11 12]
 [13 14]
 [15 16]
 [17 18]]


[array([[11, 12],
        [13, 14]]),
 array([[15, 16],
        [17, 18]])]

Split the 2-D array into two 2-D arrays along rows

In [65]:
my_array = np.array([[11, 12], [13, 14], [15, 16], [17, 18]])

print(my_array)

new_array = np.array_split(my_array, 2, axis=1)

new_array

[[11 12]
 [13 14]
 [15 16]
 [17 18]]


[array([[11],
        [13],
        [15],
        [17]]),
 array([[12],
        [14],
        [16],
        [18]])]

### NumPy searching arrays

Use `where()` method to search an array for a certain value. It returns the index number.

In [66]:
my_array = np.array([11, 12, 13, 14, 15])

np.where(my_array == 13)

(array([2], dtype=int64),)

It means that 13 is present at index 2

In [67]:
# indexes where the values are even
np.where(my_array%2 == 0)

(array([1, 3], dtype=int64),)

**`searchsorted()`**

In [68]:
my_array = np.array([17, 16, 18, 19])

new_array = np.searchsorted(my_array, 17)

print(new_array)

2


The number 17 should be inserted on index 2 to remain the sort order.

In [69]:
my_array = np.array([17, 16, 18, 19])

new_array = np.searchsorted(my_array, 18, side='right')

print(new_array)

3


The number 18 should be inserted on index 3 to remain the sort order.

### Sorting arrays

Use `sort()` function to sort a specified array

In [70]:
my_array = np.array([301, 112, 20, 121])

print(np.sort(my_array))

[ 20 112 121 301]


In [71]:
my_array = np.array(['yellow', 'Orange', 'red'])

print(np.sort(my_array))

['Orange' 'red' 'yellow']


In [72]:
my_array = np.array([[13, 21, 42], [51, 3, 12]])
print(my_array)
print("Sorted array:\n",np.sort(my_array))

[[13 21 42]
 [51  3 12]]
Sorted array:
 [[13 21 42]
 [ 3 12 51]]


**Haapy Learning!!**